# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TestCase123.
      - MYSQL_DATABASE=review_db
    ports:
      - 127.0.0.1:3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
